# Generated by Django 6.0.6 on 2026-06-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('grupo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pendiente', 'Pendiente'), ('inactivo', 'Inactivo')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('ia', 'Mentor IA'), ('sistema', 'Sistema')], default='usuario', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
